config:
  base:
    endpoint: http://service-products/api/v2/products

server:
  port: 8090
spring:
  application:
    name: service-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
